### ISSUE TITLE
Error ortográfico

### ISSUE THREAD

**Issue by jforni** [Agustin978/Rolling_ProyectoFinal#38]
En el modal de error de inicio de sesión, corrijan la palabra "secion" ya que lo correcto es "sesión".
Adjunto imagen de evidencia. 

![Screenshot_20230809_172221_Chrome](https://github.com/Agustin978/Rolling_ProyectoFinal/assets/6042663/dcbeb384-00da-4dd2-9b44-2726d3b20b09)

**Comment by NavarroLeandro** [comment]
Cambiado el "secion" por "sesión" en los archivos correspondientes
