### ISSUE TITLE
Incongruencia entre la tabla productos disponibles con el selector en la opción de editar producto

### ISSUE THREAD

**Issue by jforni** [Agustin978/Rolling_ProyectoFinal#40]
Noto que la tabla de productos disponibles está tomando los datos de una fuente y cuando entro a editar un producto, en el selector de  "Categoría" del producto están cargados de otra fuente. Lo ideal es que tanto en uno y otro lado sea exactamente lo mismo. 
Adjunto imagenes:
![Tabla productos](https://github.com/Agustin978/Rolling_ProyectoFinal/assets/6042663/e3ba9652-83cd-46f4-bcd5-037bebdca9fb)
![Seleccion en editar](https://github.com/Agustin978/Rolling_ProyectoFinal/assets/6042663/9fa97fc7-9b96-4774-bd0c-6b8cb96ac1b6)

**Comment by Martinserrano724** [comment]
lista la correccion de productos y en editar productos
